### ISSUE TITLE
Failure during installation of nfs-subdir-external-provisioner

### ISSUE THREAD

**Issue by gkoutsog** [sassoftware/viya4-iac-k8s#34]
Hi,

We are trying to install this to our bare-metal servers and executing the oss-k8s.sh script through a docker container.
Works well until it comes to the nfs-subdir-external-provisioner installation task, where it fails. 

Short error:
```yaml
fatal: [localhost]: FAILED! => {"changed": false, "command": "/usr/local/bin/helm --version=4.0.16 --repo=https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/ upgrade -i --reset-values --wait --create-namespace -f=/tmp/tmpszu05z7m.yml nfs-subdir-external-provisioner-default nfs-subdir-external-provisioner", "msg": "Failure when executing Helm command. Exited 1.\nstdout: Release \"nfs-subdir-external-provisioner-default\" does not exist. Installing it now.\n\nstderr: Error: timed out waiting for the condition\n", "stderr": "Error: timed out waiting for the condition\n", "stderr_lines": ["Error: timed out waiting for the condition"], "stdout": "Release \"nfs-subdir-external-provisioner-default\" does not exist. Installing it now.\n", "stdout_lines": ["Release \"nfs-subdir-external-provisioner-default\" does not exist. Installing it now."]}
```

Nothing happens, sits there and waits and times out after about 5 minutes.

This didn't provide so much information, so we run the whole thing with "-vvvvv" and got the following:

```yaml

TASK [kubernetes/storage/nfs-subdir-external-provisioner : Setting up default storage for cluster using nfs-subdir-external-provisioner] ******************************************************************
task path: /viya4-iac-k8s/roles/kubernetes/storage/nfs-subdir-external-provisioner/tasks/main.yaml:9
Friday 26 August 2022  12:16:12 +0000 (0:00:01.391)       0:06:55.428 *********
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp `"&& mkdir "` echo $HOME/.ansible/tmp/ansible-tmp-1661516172.2773957-6455-25144315223314 `" && echo ansible-tmp-1661516172.2773957-6455-25144315223314="` echo $HOME/.ansible/tmp/ansible-tmp-1661516172.2773957-6455-25144315223314 `" ) && sleep 0'
Using module file /viya4-iac-k8s/.ansible/collections/ansible_collections/kubernetes/core/plugins/modules/helm.py
<127.0.0.1> PUT /viya4-iac-k8s/.ansible/tmp/ansible-local-802z26hs1fm/tmpjaxv60vk TO /viya4-iac-k8s/.ansible/tmp/ansible-tmp-1661516172.2773957-6455-25144315223314/AnsiballZ_helm.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /viya4-iac-k8s/.ansible/tmp/ansible-tmp-1661516172.2773957-6455-25144315223314/ /viya4-iac-k8s/.ansible/tmp/ansible-tmp-1661516172.2773957-6455-25144315223314/AnsiballZ_helm.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /viya4-iac-k8s/.ansible/tmp/ansible-tmp-1661516172.2773957-6455-25144315223314/AnsiballZ_helm.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /viya4-iac-k8s/.ansible/tmp/ansible-tmp-1661516172.2773957-6455-25144315223314/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "command": "/usr/local/bin/helm --version=4.0.16 --repo=https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/ upgrade -i --reset-values --wait --create-namespace -f=/tmp/tmpfze9iz5i.yml nfs-subdir-external-provisioner-default nfs-subdir-external-provisioner",
    "invocation": {
        "module_args": {
            "api_key": null,
            "atomic": false,
            "binary_path": null,
            "ca_cert": null,
            "chart_ref": "nfs-subdir-external-provisioner",
            "chart_repo_url": "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/",
            "chart_version": "4.0.16",
            "context": null,
            "create_namespace": true,
            "disable_hook": false,
            "force": false,
            "history_max": null,
            "host": null,
            "kubeconfig": "/workspace/ucr-oss-kubeconfig.conf",
            "name": "nfs-subdir-external-provisioner-default",
            "namespace": "kube-system",
            "purge": true,
            "release_name": "nfs-subdir-external-provisioner-default",
            "release_namespace": "kube-system",
            "release_state": "present",
            "release_values": {
                "nfs": {
                    "mountOptions": [
                        "noatime",
                        "nodiratime",
                        "rsize=262144",
                        "wsize=262144"
                    ],
                    "path": "/srv/nfs/kubernetes/sc/default",
                    "server": "xx.xx.xx.xx"
                },
                "storageClass": {
                    "archiveOnDelete": "false",
                    "defaultClass": "true",
                    "name": "default"
                }
            },
            "replace": false,
            "skip_crds": false,
            "timeout": null,
            "update_repo_cache": false,
            "validate_certs": true,
            "values": {
                "nfs": {
                    "mountOptions": [
                        "noatime",
                        "nodiratime",
                        "rsize=262144",
                        "wsize=262144"
                    ],
                    "path": "/srv/nfs/kubernetes/sc/default",
                    "server": "xx.xx.xx.xx"
                },
                "storageClass": {
                    "archiveOnDelete": "false",
                    "defaultClass": "true",
                    "name": "default"
                }
            },
            "values_files": [],
            "wait": true,
            "wait_timeout": null
        }
    },
    "msg": "Failure when executing Helm command. Exited 1.\nstdout: Release \"nfs-subdir-external-provisioner-default\" does not exist. Installing it now.\n\nstderr: Error: timed out waiting for the condition\n",
    "stderr": "Error: timed out waiting for the condition\n",
    "stderr_lines": [
        "Error: timed out waiting for the condition"
    ],
    "stdout": "Release \"nfs-subdir-external-provisioner-default\" does not exist. Installing it now.\n",
    "stdout_lines": [
        "Release \"nfs-subdir-external-provisioner-default\" does not exist. Installing it now."
    ]
}
```

The helm chart is available and can be installed, but the feeling is that the timeout is happening in the kubernetes cluster level.

Any help is appreciated!

**Comment by thpang** [comment]
Did you check the helm chart as it was trying to install the deployment? Were you able to view the pods being started and check their events to see what/why they were delayed? This sounds like a configuration issue with your infra. I'd need to know more about the inventory and ansible-vars.yaml file. Also did you verify that from the Jump server the NFS mounts to the NFS server were correct? Let me know what your find.

**Comment by gkoutsog** [comment]
I also think that it sounds like a misconfiguration from our side, I just have a hard time figuring out where exactly.
We have tested and installed the helm chart manually per the instructions on https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/.  

All the hosts sit in the same vlan ( /24) and there is no access list or firewall blocking communication.

I am suspicious about kube-vip, keep thinking that the values there are not matching the rest:

```yaml
kubernetes_cluster_name    : "{{ prefix }}-oss" # NOTE: only change the prefix value above
kubernetes_version         : "1.23.9"
kubernetes_upgrade_allowed : true
kubernetes_arch            : "{{ vm_arch }}"
kubernetes_cni             : "calico"       
kubernetes_cri             : "containerd"   
kubernetes_service_subnet  : "10.42.0.0/16"
kubernetes_pod_subnet      : "10.43.0.0/16"

kubernetes_vip_version              : "0.4.4"
kubernetes_vip_interface            : ""
kubernetes_vip_ip                   : "10.18.0.175"
kubernetes_vip_loadbalanced_dns     : "dev-viya4-vip.xx.xxx.xxx.xx"
kubernetes_vip_cloud_provider_range : "10.18.0.100-10.18.0.125"

```
