### ISSUE TITLE
fix: (IAC-1247) OS Specific variables created without guardrails or OS validation

### ISSUE THREAD

**Issue by thpang** [sassoftware/viya4-iac-k8s#80]
Found this variable: `kubernetes_cri_deb_rev` located [here](https://github.com/sassoftware/viya4-iac-k8s/blob/c41a387a0a70be5848fe26963ab9803913ae7ea4/roles/kubernetes/cri/containerd/defaults/main.yaml#L14) and being used [here](https://github.com/sassoftware/viya4-iac-k8s/blob/main/roles/kubernetes/cri/containerd/tasks/main.yaml#L105-L111).

The code should have an OS guard for Ubuntu and the variable used for revisions should be just tagged as such and not identified as `deb` anything.

Here is the mocked up task. The when statement is written so both must be true
```yaml
- name: set containerd.io package debian revision if not specified
  set_fact:
    kubernetes_cri_deb_rev: "-*"
  when:
     - kubernetes_cri_version | regex_search("^(\d+\.)(\d+\.)(\d+)$")
     - ansible_distribution == "Ubuntu" and (ansible_distribution_version == "20.04" or ansible_distribution_version == "22.04")
  tags:
    - install
    - update
```
